---
title: VeritasHomesNW
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: Neil@VeritasHomesNW.com
description: VeritasHomesNW description goes here.
baseurl: ''
url: http://veritashomesnw.siteleaf.net
twitter_username: jacobrossdobson
github_username: jakedobson
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
