---
title: VeritasHomesNW
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: default
    identifier: 
    images:
    - image: 
      alt: 
    address:
      street: 
      locale: 
    links:
      blog: 
      map: 
      listing: 
    details:
      size: 
      bed: 
      bath: 
      feature: 
    dates:
      start:
        date: 
      end:
        date: 
baseurl: 
links:
  blog:
    title: Blog
    url: http://medium.com
  projects:
    title: Projects
    url: "#projects"
  aboutUs:
    title: About Us
    url: "#aboutUs"
  fb:
    title: Facebook
    link: http://facebook.com
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
footer:
  phone: "(206) 883-5212"
  email: Neil@VeritasHomesNW.com
  office: 2701 California Ave SW, Seattle, WA 98116
