---
title: VeritasHomesNW
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: VeritasHomesNW description goes here.
baseurl: 
url: http://veritashomesnw.siteleaf.net
headerTitle:
  topText: VERITAS
  bottomText: TRUTH TO HOME SOLUTIONS
logoText: Logo
links:
  blog: Blog
  projects: Projects
  aboutUs: About Us
  fb: Facebook
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
footer:
  phone: "(206) 883-5212"
  email: Neil@VeritasHomesNW.com
  office: 2701 California Ave SW, Seattle, WA 98116
